Fatal error: exception Failure("test")
Raised at file "inline_test.ml", line 5, characters 8-24
Called from file "inline_test.ml", line 8, characters 2-5
Called from file "inline_test.ml", line 11, characters 12-17
Called from file "inline_test.ml", line 14, characters 5-8
Called from file "inline_test.ml", line 18, characters 2-6
